name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter


  # ğŸ“Œ Gestion d'Ã©tat (architecture BLoC)
  uuid: ^4.5.1
  flutter_bloc: ^8.1.3     # Gestion de lâ€™Ã©tat avec Cubit/BLoC
  equatable: ^2.0.5        # Simplifie la comparaison des objets (utile pour les states)

  # ğŸŒ API REST
  http: ^1.2.2             # RequÃªtes HTTP (si besoin de consommer dâ€™autres API)

  # ğŸ”¥ Firebase
  firebase_core: ^4.1.0    # Base obligatoire pour initialiser Firebase
  cloud_firestore: ^6.0.1  # Base de donnÃ©es Firestore (CRUD des utilisateurs)
  firebase_storage: ^13.0.1 # Stockage des fichiers (photo de profil des utilisateurs)
  # firebase_storage: ^12.0.1 # (âš ï¸ ancienne version qui causait des conflits)

  # ğŸ“· Gestion des images
  image_picker: ^1.1.2     # SÃ©lectionner une image (camÃ©ra / galerie)
  path_provider: ^2.1.2   
  path: ^1.9.0   # # RÃ©cupÃ©rer un rÃ©pertoire local pour sauvegarde temporaire

  # ğŸ“² QR Code
  qr_flutter: ^4.1.0       # GÃ©nÃ©ration de QR Code pour chaque utilisateur
  mobile_scanner: ^5.2.3   # Scanner QR Code avec la camÃ©ra
  audioplayers: ^6.0.0

  # ğŸ¨ IcÃ´nes Cupertino (style iOS)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0    # Analyse statique du code (bonnes pratiques)

flutter:
  uses-material-design: true # Active lâ€™utilisation des Material Icons
